export const movies = [
  {
    id: "1",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    views: 124500,
    year: 2014,
    matchRate: 98,
    ageRating: "13+",
    duration: "2h 49m",
    ratings: [
      { user: "john", score: 5 },
      { user: "alice", score: 4 },
      { user: "somchai", score: 5 },
    ],
  },
  {
    id: "2",
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    category: "Action",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    views: 95400,
    year: 2008,
    matchRate: 99,
    ageRating: "16+",
    duration: "2h 32m",
    ratings: [
      { user: "mark", score: 5 },
      { user: "kitti", score: 5 },
    ],
  },
  {
    id: "3",
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    views: 110200,
    year: 2010,
    matchRate: 97,
    ageRating: "13+",
    duration: "2h 28m",
    ratings: [
      { user: "sam", score: 4 },
      { user: "chao", score: 5 },
    ],
  },
  {
    id: "4",
    title: "The Conjuring",
    description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=k10ETZ42q5o",
    views: 82000,
    year: 2013,
    matchRate: 94,
    ageRating: "18+",
    duration: "1h 52m",
    ratings: [
      { user: "ghosthunter", score: 4 },
      { user: "scaredycat", score: 3 },
    ],
  },
  {
    id: "5",
    title: "The Hangover",
    description: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=tcdUhdOlz9M",
    views: 74000,
    year: 2009,
    matchRate: 92,
    ageRating: "18+",
    duration: "1h 40m",
    ratings: [
      { user: "laughoutloud", score: 5 },
      { user: "grumpy", score: 2 },
    ],
  },
  {
    id: "6",
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    views: 89000,
    year: 2019,
    matchRate: 96,
    ageRating: "18+",
    duration: "2h 12m",
    ratings: [
      { user: "cinephile", score: 5 },
      { user: "bongjoonho", score: 5 },
    ],
  },
  {
    id: "7",
    title: "Shutter",
    description: "A young photographer and his girlfriend discover mysterious shadows in their photographs after a tragic road accident.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=yW6aKj-4E0s",
    views: 63000,
    year: 2004,
    matchRate: 95,
    ageRating: "18+",
    duration: "1h 37m",
    ratings: [
      { user: "ananda", score: 5 },
      { user: "horrorgirl", score: 4 },
    ],
  },
  {
    id: "8",
    title: "Bad Genius",
    description: "Lynn, a genius high school student who makes money by cheating tests, receives a new task that leads her to set foot on Sydney, Australia.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=CLek_u8tU4g",
    views: 91000,
    year: 2017,
    matchRate: 98,
    ageRating: "13+",
    duration: "2h 10m",
    ratings: [
      { user: "student", score: 5 },
      { user: "teacher", score: 4 },
    ],
  },
  {
    id: "9",
    title: "Pee Mak",
    description: "Mak returns from war to invite his friends to meet his beautiful wife Nak. But rumors start spreading that Nak is actually a ghost.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=vVj4I7pX_P4",
    views: 120000,
    year: 2013,
    matchRate: 97,
    ageRating: "13+",
    duration: "1h 55m",
    ratings: [
      { user: "mario", score: 5 },
      { user: "davika", score: 5 },
    ],
  }
];

