export const CATEGORIES = [
  "Action",
  "Sci-Fi",
  "Drama",
  "Comedy",
  "Horror",
  "Thriller",
  "Romance",
  "Adventure",
  "Fantasy",
  "Animation",
  "Biography",
  "Documentary",
  "Family",
  "Music",
  "Mystery",
  "Sport",
  "Western",
];

export const CATEGORY_TITLE_MAPPING: Record<string, string> = {
  "Action": "แอคชั่น",
  "Sci-Fi": "ไซไฟ / วิทยาศาสตร์",
  "Horror": "สยองขวัญ",
  "Comedy": "คอมเมดี้ / ตลก",
  "Thriller": "ระทึกขวัญ",
  "Drama": "ดราม่า",
  "Romance": "โรแมนติก",
  "Adventure": "ผจญภัย",
  "Fantasy": "แฟนตาซี",
  "Animation": "แอนิเมชัน",
  "Biography": "ชีวประวัติ",
  "Documentary": "สารคดี",
  "Family": "ครอบครัว",
  "Music": "ดนตรี",
  "Mystery": "ลึกลับ / ไขปริศนา",
  "Sport": "กีฬา",
  "Western": "คาวบอย / ตะวันตก",
};
